version: '3'
services:
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
      - "7001:7001"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./scripts:/scripts
    command: ["cassandra", "-f", "-R"]

volumes:
  cassandra-data:
