version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7000:7000"
      - "7001:7001"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-data:/var/lib/cassandra
    command: ["cassandra", "-f", "-R"]

    # Initialization scripts to create keyspace and tables
  init-cqlsh:
    image: cassandra:latest
    depends_on:
      - cassandra
    command: ["cqlsh", "cassandra", "--file", "/scripts/init.cql"]
    volumes:
      - ./init.cql:/scripts/init.cql

volumes:
  cassandra-data:
